### ISSUE TITLE
PG (pin #6) should be pulled-up to VCC (pin #9)?

### ISSUE THREAD

**Issue by thisisgregm** [TheMariday/bappr#4]
Hi. I used the same IC for 12V to 5V regulator. I wanted to compare them out of curiosity. Seems like your pin #6 of the IC (PG signal) is floating, but based on the datasheet it should be pulled up to VCC. Doesn it actually work like that? Would be good to know.

This is what Diodes Inc says on Pin Description page in the datasheet:

_**Power-Good. PG is an open-drain output that is pulled to GND when the output voltage is out of its regulation limits or during soft-start. Connect an external pull-up resistor from PG to VCC.**_

**Comment by TheMariday** [comment]
Hi there, thank you for the comment!

From my understanding, power good is an output and if you're reading the voltage at this pin, pulling it to VCC is essential so that it can open drain to ground when disabled.

However as I'm not interested in reading it, it's perfectly happy to be left floating.
